// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZq-AYXIKenTi-WLkeO424g9HDllHs2Q4',
    appId: '1:958353387131:web:29169642da371e9a9e7cde',
    messagingSenderId: '958353387131',
    projectId: 'vjit-study-vault',
    authDomain: 'vjit-study-vault.firebaseapp.com',
    storageBucket: 'vjit-study-vault.firebasestorage.app',
    measurementId: 'G-EVMLLVHLFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZq-AYXIKenTi-WLkeO424g9HDllHs2Q4',
    appId: '1:958353387131:android:c3d4965a7aa354a09e7cde',
    messagingSenderId: '958353387131',
    projectId: 'vjit-study-vault',
    storageBucket: 'vjit-study-vault.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZq-AYXIKenTi-WLkeO424g9HDllHs2Q4',
    appId: '1:958353387131:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '958353387131',
    projectId: 'vjit-study-vault',
    storageBucket: 'vjit-study-vault.firebasestorage.app',
    iosBundleId: 'com.example.vjitstudyvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZq-AYXIKenTi-WLkeO424g9HDllHs2Q4',
    appId: '1:958353387131:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '958353387131',
    projectId: 'vjit-study-vault',
    storageBucket: 'vjit-study-vault.firebasestorage.app',
    iosBundleId: 'com.example.vjitstudyvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZq-AYXIKenTi-WLkeO424g9HDllHs2Q4',
    appId: '1:958353387131:web:29169642da371e9a9e7cde',
    messagingSenderId: '958353387131',
    projectId: 'vjit-study-vault',
    authDomain: 'vjit-study-vault.firebaseapp.com',
    storageBucket: 'vjit-study-vault.firebasestorage.app',
    measurementId: 'G-EVMLLVHLFP',
  );
}