name: Build Flutter PWA

on:
  push:
    branches: [ main ]
    # Only build when these files change (NOT when materials.json changes)
    paths:
      - 'lib/**'
      - 'web/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - '!web/materials.json'  # Exclude materials.json
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'web/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - '!web/materials.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'
        channel: 'stable'
        cache: true
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Build Flutter web
      run: flutter build web --release --web-renderer html
      
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: vjitstudyvault-pwa
        directory: build/web
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}